---
kind: book
title: PrismaÂ® Cloud Application Security
author: Prisma Cloud Tech Docs
ditamap: prisma-cloud-application-security
dita: techdocs/en_US/dita/prisma/prisma-cloud/prisma-cloud-application-security
graphics: techdocs/en_US/dita/_graphics/uv/prisma/prisma-cloud/prisma-cloud-application-security
github:
  owner: PaloAltoNetworks
  repo: prisma-cloud-docs
  bookdir: application-security
  branch: application-security
---
kind: chapter
name: Application Security
dir: application-security
topics:
  - name: Application Security
    file: application-security.adoc
  - name: Familiarize Yourself with Application Security
    file: familiarize-application-security.adoc
  - name: Supported Technologies
    file: supported-technologies.adoc
  - name: Get Started with Application Security
    dir: get-started
    topics:
      - name: Get Started with Application Security
        file: get-started.adoc
      - name: Enable Application Security
        file: enable-application-security.adoc
      - name: Application Security License Types
        file: application-security-license-types.adoc
      - name: Manage Roles and Permissions
        file: manage-roles-permissions.adoc
      - name: Connect Code and Build Providers
        dir: connect-code-and-build-providers
        topics:
          - name: Connect Code and Build Providers
            file: connect-code-and-build-providers.adoc
          - name: Code Repositories
            dir: code-repositories
            topics:
              - name: Code Repositories
                file: code-repositories.adoc
              - name: AWS CodeCommit
                file: add-aws-codecommit.adoc
              - name: Azure Repos
                file: add-azurerepos.adoc
              - name: Bitbucket
                file: add-bitbucket.adoc
              - name: Bitbucket Data Center/ Server
                file: add-bitbucket-server.adoc
              - name: GitHub
                file: add-github.adoc
              - name: Github Server
                file: add-github-server.adoc
              - name: GitLab
                file: add-gitlab.adoc
              - name: Gitlab Self-managed
                file: add-gitlab-selfmanaged.adoc
          - name: CI/CD Runs
            dir: ci-cd-runs
            topics:
              - name: CI/CD Runs
                file: ci-cd-runs.adoc
              - name: Azure Pipelines
                file: add-azure-pipelines.adoc
              - name: AWS Code Build
                file: add-aws-codebuild.adoc
              - name: Checkov
                file: add-checkov.adoc
              - name: CircleCI
                file: add-circleci.adoc
              - name: GitHub Actions
                file: add-github-actions.adoc
              - name: GitLab Runner
                file: add-gitlab-runner.adoc
              - name: Jenkins Server
                file: add-jenkins.adoc
              - name: Terraform Cloud (Run Tasks)
                file: add-terraform-run-tasks.adoc
              - name: Terraform Cloud (Sentinel)
                file: add-terraform-cloud-sentinel.adoc
              - name: Terraform Enterprise (Run Tasks)
                file: add-terraform-enterprise-run-tasks.adoc
              - name: Terraform Enterprise (Sentinel)
                file: add-terraform-enterprise.adoc
          - name: CI/CD Systems
            dir: ci-cd-systems
            topics:
              - name: CI/CD Systems
                file: ci-cd-systems.adoc
              - name: CircleCI
                file: add-circleci-cicd-system.adoc
              - name: Jenkins Server
                file: add-jenkins-cicd-system.adoc
          - name: Package Registries
            file: add-private-registries.adoc
      - name: Non-Default Branch Scan
        file: non-default-branch-scan.adoc
      - name: Application Security Settings
        dir: application-security-settings
        topics:
          - name: Application Security Settings
            file: application-security-settings.adoc
          - name: Enable Notifications
            file: enable-notifications.adoc
          - name: Exclude Paths
            file: exclude-paths.adoc
#          - name: Code Reviews and PR Comments
#            file: code-reviews-pr-comments.adoc
      - name: Add Prisma Cloud Code Security Scanner as a Pre-Receive Hook
        file: add-pre-receive-hooks.adoc
  - name: Manage Transporter (Network Tunnels)
    dir: manage-network-tunnel
    topics:
      - name: Manage Transporter (Network Tunnels)
        file: manage-network-tunnel.adoc
      - name: Transporter Connectivity Overview
        file: transporter-connectivity-overview.adoc
      - name: Set Up Transporter Network Tunnels using Docker Containers
        file: deploy-transporter-docker.adoc
      - name: Set Up Transporter Network Tunnels using Helm Charts
        file: deploy-transporter-helmcharts.adoc
      - name: Transporter Health Check
        file: transporter-health-check.adoc
      - name: Select Transporter and ensure Domain Name consistency
        file: select-transporter-domain-consistency.adoc
  - name: Visibility
    dir: visibility
    topics:
      - name: Visibility
        file: visibility.adoc
      - name: Repositories
        file: repositories.adoc
      - name: Technologies
        dir: technologies
        topics:
          - name: Technologies
            file: technologies.adoc
          - name: Technology Overview
            file: technology-overview.adoc
          - name: VCS 3rd Parties
            file: vcs-third-parties.adoc
          - name: Jenkins Plugins
            file: jenkins-plugins.adoc
          - name: Pipeline Tools
            file: pipeline-tools.adoc
      - name: SBOM
        dir: sbom
        topics:
          - name: SBOM
            file: sbom.adoc
          - name: Package Dependency Graph
            file: package-dependency-graph.adoc
  - name: Risk Management
    dir: risk-management
    topics:
      - name: Risk Management
        file: risk-management.adoc
      - name: Monitor and Manage Code Build Issues
        dir: monitor-and-manage-code-build
        topics:
          - name: Monitor and Manage Code Build Issues
            file: monitor-and-manage-code-build.adoc
          - name: Monitor Code Build Issues
            file: monitor-code-build-issues.adoc
          - name: Enforcement
            file: enforcement.adoc
          - name: Drift Detection
            file: drift-detection.adoc
          - name: Software Composition Analysis (SCA)
            dir: software-composition-analysis
            topics:
              - name: Software Composition Analysis (SCA)
                file: software-composition-analysis.adoc
              - name: License Compliance in Software Composition Analysis (SCA)
                file: license-compliance-in-sca.adoc
              - name: Troubleshoot Software Composition Analysis (SCA) Issues
                file: sca-troubleshoot.adoc
          - name: Secrets Scanning
            file: secrets-scanning.adoc
          - name: Terraform Module Scanning
            file: terraform-module-scan.adoc
          - name: Pull Request Scanning
            file: pull-request-scan.adoc
          - name: Fix Code Issues
            file: fix-code-issues.adoc
          - name: Suppress Code Issues
            file: suppress-code-issues.adoc
          - name: Traceability and Tagging
            file: traceability-and-tagging.adoc
      - name: CI/CD Risks
        file: ci-cd-risks.adoc        
      - name: Risk Indicators
        file: risk-indicators.adoc         
  - name: IDEs
    dir: ides
    topics:
      - name: IDEs
        file: ides.adoc
      - name: VS Code
        file: connect-vscode.adoc             
      - name: Jetbrains
        file: connect-jetbrains.adoc
  - name: CLI
    dir: cli
    topics:
      - name: CLI
        file: cli.adoc
      - name: Get Started with CLI
        file: cli-get-started.adoc
      - name: CLI Command Reference
        file: cli-cmnd-ref.adoc
      - name: Suppress and Skip Policies
        file: suppress-skip.adoc 
      - name: Hard and Soft Fails
        file: cli-hard-soft-fail.adoc
      - name: Scan Credentials and Secrets
        file: cli-scan-credential-secrets.adoc
      - name: Review Scan Results
        file: cli-review-scan-results.adoc
      - name: Checkov Output on Prisma Cloud Console
        file: cli-checkov-output-prisma-cloud.adoc
      - name: Handle Variables
        file: cli-handle-variables.adoc
      - name: Policies
        dir: policies
        topics:        
          - name: Policies
            file: cli-policies.adoc
          - name: Custom Policies
            dir: cli-custom-policies
            topics:
            - name: Custom Policies
              file: cli-policies-custom.adoc
            - name: Custom Python Policies
              file: cli-custom-python-policies.adoc
            - name: Custom Yaml Policies
              file: cli-custom-yaml-policies.adoc
            - name: Share Custom Policies
              file: cli-custom-policies-share.adoc
            - name: Custom Policy Examples
              file: custom-policies-examples.adoc
      - name: CLI Integrations
        dir: cli-integrations
        topics:
          - name: CLI Integrations
            file: cli-integrations.adoc
          - name: Bitbucket Cloud Pipelines  
            file: cli-int-bb-cloud-pipeline.adoc
          - name: Docker
            file: cli-int-docker.adoc
          - name: GitHub Actions 
            file: cli-int-gh-actions.adoc
          - name: GitLab CI
            file: cli-intgl-ci.adoc
          - name: Jenkins  
            file: cli-int-jenkins.adoc
          - name: Kubernetes
            file: cli-int-kubernetes.adoc
          - name: OpenAI
            file: cli-int-openai.adoc  
          - name: Pre-Commit Hooks
            file: cli-int-precommit.adoc
      - name: CLI Scan Examples
        dir: cli-scan-examples
        topics:
          - name: CLI Scan Examples
            file: cli-scan-examples.adoc
          - name: Scan Ansible Configurations
            file: cli-scan-eg-ansible.adoc 
          - name: Scan Argo Workflows Configurations
            file: cli-scan-eg-argo.adoc
          - name: Scan AWS CDK Configurations
            file: cli-scan-eg-aws-cdk.adoc
          - name: Scan AWS SAM Framework Configurations
            file: cli-scan-eg-aws-sam.adoc
          - name: Scan Azure ARM Templates Configurations
            file: cli-scan-eg-azure-arm.adoc
          - name: Scan Azure Bicep Configurations
            file: cli-scan-eg-azure-bicep.adoc
          - name: Scan Azure Pipeline Configurations
            file: cli-scan-eg-azure-pipeline.adoc
          - name: Scan Bitbucket Configurations
            file: cli-scan-eg-bb.adoc
          - name: Scan CloudFormation Configurations
            file: cli-scan-eg-cloudform.adoc
          - name: Scan Dockerfile Configurations
            file: cli-scan-eg-docker.adoc
          - name: Scan GitHub Configurations
            file: cli-scan-eg-gh.adoc
          - name: Scan GitLab Configurations
            file: cli-scan-eg-gl.adoc
          - name: Scan Helm Chart Configurations
            file: cli-scan-eg-helm.adoc
          - name: Scan Kustomize kustomizations Configurations
            file: cli-scan-eg-kustomize.adoc
          - name: Scan Kubernetes configurations
            file: cli-scan-eg-kubernetes.adoc
          - name: Scan OpenAPI Configurations
            file: cli-scan-eg-openai.adoc
          - name: Scan SCA
            file: cli-scan-eg-sca.adoc
          - name: Scan Serverless Framework Configurations
            file: cli-scan-eg-serverless.adoc
          - name: Scan Terraform Configurations
            file: cli-scan-eg-tf.adoc
          - name: Scan Terraform Plan Configurations
            file: cli-scan-eg-tf-plan.adoc











        
---
